name: togo_cubit
description: Store and Cart example using Cubit in Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  gap: ^2.0.0
  uuid: ^3.0.4
  equatable: ^2.0.3
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  flutter_elegant_number_button: ^0.0.6
  badges: ^2.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  supabase: ^0.0.1-dev.22
  bloc: ^7.0.0
  flutter_bloc: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true